# Generated by Django 5.1 on 2024-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_tablet_usertablet_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertablet',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usertablet',
            name='start_time',
        ),
        migrations.AddField(
            model_name='usertablet',
            name='alarm_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
